### ISSUE TITLE
.glb mint preview appearing too large vertically in full screen mode.

### ISSUE THREAD

**Issue by ZOOTGHOST** [hicetnunc2000/hicetnunc#1316] opened 2021-10-22 16:36 UTC
*Please fill out the following Bug Report Template

**Describe the bug**
When previewing .glb (exported from blender on mac) it appears perfectly. Then when full screen preview is pressed the .glb appears vertically larger then the computer screen. Once full screen mode is switched back to regular preview the file appears too large, zoomed in with no ability to correct.

**To Reproduce**
1. Upload .glb file for mint preview
2. Click on full screen mode
3. See error

**Expected behavior**
3d model will vertically appear longer then the screen vertically.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: High Sierra - 10.12.6
 - Browser - Chrome
 - Version - 94.0.4606.81 (Official Build) (x86_64)

**Additional context**
Once .glb is minted it appears perfectly to scale in Full screen and normal mode.

**Comment by melMass** [comment] 2022-04-19 09:39
Dupe of #1375

**Closed as completed by melMass** 2022-04-19 09:39 UTC
Labels: bug, duplicate
