### ISSUE TITLE
I cannot mint new OBJKTs, the wallet confirmation window does not appear!

### ISSUE THREAD

**Issue by psychedelicnature** [hicetnunc2000/hicetnunc#547] opened 2021-04-21 05:05 UTC
**BUG**
After I click to mint an OBJKT at the "preview" screen, *the "preparing OBJKT" screen runs forever* (screenshot), the Temple tezos *wallet confirmation window does not appear* in order I can confirm the minting transaction! BUT, when I buy a new OBJKT from someone else to my wallet, the Temple wallet confirmation window shows up normally and I am able to buy OBJKTs. Why can't I mint new OBJKTs?? This kind of error never occured to me before, and I've always used the browser Brave and the Temple - Tezos Wallet normally.

**Expected behavior**
I expected the confirmation window of my wallet to appear as it always did so I can confirm transaction and complete the minting of my work!

**Screenshots**
![bug](https://user-images.githubusercontent.com/82925229/115498715-750a0980-a244-11eb-9c47-91a794fc5f9b.JPG)

**Desktop**
 - Windows 10
 - Browser Brave

**Additional context**
 my wallet address:  tz1iwXebhEReFRxM7n5DhRGdaBXaTGTEaG6C

*Thank You!*

**Comment by skenaja** [comment] 2021-04-21 15:57
@onlyone4onlyone - can you check https://github.com/hicetnunc2000/hicetnunc/issues/466 to see if you've got the same issue?

**Comment by nancybakercahill** [comment] 2021-04-24 00:27
Hi- same boat. Have tried in vain to mint a short video after creating and funding a kukai wallet with tezos. unsynced, resynced, same problem. Is this an ongoing bug and/or anyoneknow the solution?

**Comment by skenaja** [comment] 2021-04-24 09:28
@nancybakercahill - There was also a separate network issue earlier today relating to the 3rd party site (https://mainnet.smartpy.io) that connects the site to the wallet and the tezos network. These appear to have been resolved, so please try again. If you're still experiencing problems, can you also check the dev tools console (see #466) to see if you're experiencing the same trouble?

Closing as duplicate of #466, will re-open if new information is added to this ticket that relates to a different problem.

**Closed as completed by skenaja** 2021-04-24 09:28 UTC
Labels: bug
