### ISSUE TITLE
My work doesn't appear in buyer's collection

### ISSUE THREAD

**Issue by neverhood311** [hicetnunc2000/hicetnunc#426] opened 2021-04-06 15:34 UTC
**Describe the bug**
Someone bought one of my single-edition NFTs. Within the OBJKT view, they are listed as the collector. However, when viewing their collection, my OBJKT doesn't appear in their list.

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/objkt/19719 and view the collectors page
2. Notice that the wallet tz1TBa2Me3L4C7RATgRtRRWpi9EP1gqJEvuq is listed as the sole collector
3. Also note that they've listed the OBJKT for sale
4. Now go to https://www.hicetnunc.xyz/tz/tz1TBa2Me3L4C7RATgRtRRWpi9EP1gqJEvuq and view their collection
5. Notice that the OBJKT (#19719) doesn't show up in the list

**Expected behavior**
I expected to see the OBJKT in their collection, even if they've listed it for sale

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 89.0.4389.114, Edge 89.0.774.68

**Additional context**
OBJKT number: 19719
Buyer's wallet: tz1TBa2Me3L4C7RATgRtRRWpi9EP1gqJEvuq
My wallet: tz1NQZ4jDzTwojd58y4PTeETxbQXvUeQjuH1

**Comment by skenaja** [comment] 2021-04-06 19:45
They're offering it for resale, and when it's still on re-sale the objkt was transferred to a Hic et Nunc escrow wallet ready to be passed on to the buyer at the point of sale. This is why they're no longer visible in the owner's collection. The ability to keep them visible is a feature that's been requested a few times - feel free to upvote https://hicetnunc.featureupvote.com/suggestions/175980/keep-swapped-collected-objkts-as-part-of-my-collection

**Comment by oldominion** [comment] 2021-04-22 02:21
Surely it needs to be visible, or at least be accessible somewhere else, e.g. another tab that only the swapper can see.. "manage swapped items" or something?
Right now I have multiple objkts on sale, but i've forgotten which they are now, and have literally no idea how to find them in order to cancel the swap..

**Comment by violetforest** [comment] 2021-05-26 18:10
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/276

**Closed as completed by violetforest** 2021-05-26 18:10 UTC
Labels: feature-request
