### ISSUE TITLE
Update "collect for x tez" button to reflect whether price is a secondary sale

### ISSUE THREAD

**Issue by pjavid** [hicetnunc2000/hicetnunc#476] opened 2021-04-11 19:16 UTC
Currently, when viewing an OBJKT's 'info' tab, the 'collect for ...' button reflects the lowest available price (whether from Issuer or a Collector).

Requesting a subtle visual indication that distinguishes whether the visible price is from the Issuer or a Collector. 

Possible benefits from this change:
- Quickly indicates to collectors whether the sales from the default 'collect for ...' button are being directed entirely to the original artist
- Reminds collectors to check the 'collectors' tab to see what the available range of prices is. It gives them an opportunity to compare how different the default price is from the Artist's current valuation. This prevents 'undercutting' from secondary sales (.e.g. a collector listing an OBJKT at 2.9 when the Artist's price is 3.0).
- This change also lets Collectors quickly identify whether the default price reflects the artist's intended valuation (e.g. did the artist really list their piece at 1000.0? Or is this a collector trying to make a profit?)

Possible visual cues:
- An inversion of the 'collect for ...' button's color
![image](https://user-images.githubusercontent.com/9538232/114317910-44490800-9abf-11eb-9e90-f5fab93f2240.png)
- An 'x', 'o', or some other icon next to the 'collect for ...' button
![image](https://user-images.githubusercontent.com/9538232/114317993-aace2600-9abf-11eb-9877-6dc2917dc0ec.png)

**Comment by violetforest** [comment] 2021-05-26 18:13
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/342

**Closed as completed by violetforest** 2021-05-26 18:13 UTC
Labels: feature-request
