### ISSUE TITLE
Can't swap

### ISSUE THREAD

**Issue by Nek** [hicetnunc2000/hicetnunc#378] opened 2021-04-02 13:20 UTC
**Describe the bug**
A newly minted OBJKT has empty "Editions:" field and can't be swapped. The swap results in "The transaction is invalid and the node did not accept it.".

**To Reproduce**
1. Mint an OBJKT

**Expected behavior**
I expect swapping to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/132011/113418983-cf8f1300-93c6-11eb-98c1-43a5aedf3a46.png)

**Desktop (please complete the following information):**
 - OS: Windows (but I've tried it on Mac too)
 - Browser Brave
 - Version Chromium  89.0.4389.114

**Comment by Quasimondo** [comment] 2021-04-02 13:22
Maybe if you could also share the OBJKT# and maybe the tezos transaction links connected with that one it might help tracking down the cause of the error?

**Comment by Quasimondo** [comment] 2021-04-02 13:25
Also: did you actually try to use the swap tab? Whilst the empty display of "Editions" is admittedly confusing I believe that swapping should work fine - at least I could just do it for one of mine, even though it displays the same view as in your screenshot.

**Comment by Nek** [comment] 2021-04-02 14:15
Absolutely. Just let me figure out how to do this 😅 
And no, swapping doesn't work for me 😞

**Comment by Nek** [comment] 2021-04-02 14:25
https://www.hicetnunc.xyz/objkt/17477
Just tried to set a swap of 10 items for 3 Tezos.
![image](https://user-images.githubusercontent.com/132011/113424088-d8d0ad80-93cf-11eb-9e41-2e2f862c6b48.png)
![image](https://user-images.githubusercontent.com/132011/113424128-e7b76000-93cf-11eb-8448-39ccb144234e.png)

Can I provide any other info? Also, what would be a good resources to learn how to develop on Tezos?

**Comment by Quasimondo** [comment] 2021-04-02 14:49
it says "Insufficient Balance" - do you have any tezos in your wallet?

**Comment by Nek** [comment] 2021-04-02 15:14
14.716938 tez

**Comment by mescalina** [comment] 2021-04-02 15:14
But is there any reason why the total editions are gone or is it just a bug? Before it was saying 1/10 if 1 of 10 was for sale.

**Comment by Quasimondo** [comment] 2021-04-02 16:06
So it looks like you minted 5 OBJKTs but are trying to swap 10? At least that is how I interpret the "collectors" tab and which would explain the "insufficient balance" error. You cannot swap more OBJKTS that you have originally minted.

![image](https://user-images.githubusercontent.com/182098/113432694-22c09000-93de-11eb-979b-e1a4e11d09f6.png)

**Comment by Quasimondo** [comment] 2021-04-02 16:12
If you minted 10 and it displays 5 there then this sounds like a problem with the API which currently is still being worked on and which will hopefully stabilize soon.

**Comment by Nek** [comment] 2021-04-02 16:15
Thanks! I think I'm confused about several things at once. Let me look more into it.

**Comment by skenaja** [comment] 2021-04-07 20:09
Closing for now. @Nek let me know if this is still an ongoing issue, and I'll re-open it.

**Closed as completed by skenaja** 2021-04-07 20:09 UTC
