### ISSUE TITLE
Can't Upload Profile Pic or Save Profile,  Can't connect to Temple or Kukai,  Stuck on Preparing Object

### ISSUE THREAD

**Issue by jeffromeo123** [hicetnunc2000/hicetnunc#1229] opened 2021-09-27 23:17 UTC
Can't Upload Profile Pic or Save Profile within the UI. Can't connect to Temple or Kukai after Preparing Object.  Preparing Object spins and spins and never connects to a wallet.  The initial sync works though for both wallets.  I have no idea what to do.  Nothing seems to work at all.  Same last night. Thanks. 

https://tzkt.io/tz1ixbcdiMB5LPkj1StMcLtGvJ8QLrAQMTAq/operations/

**Comment by violetforest** [comment] 2021-10-01 00:55
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/1239

**Closed as completed** 2021-10-01 00:55 UTC
Labels: bug
