### ISSUE TITLE
2 problems with my NFTs

### ISSUE THREAD

**Issue by KuismaArt** [hicetnunc2000/hicetnunc#729] opened 2021-05-22 18:15 UTC
Hello. 

My name is Kuisma. I am an artist. 

My hicetnunc page:
https://www.hicetnunc.xyz/tz/tz1UV4EomFA8SUyE3d291YbNFb9uTS56pjzC

I've got 2 problems and need some help. 

Problem 1:
3 days ago I minted my work "Hyperloop" on hicetnunc in 5 copies. But on my "creations" she only appeared in one copy. In addition, this copy immediately passed into the ownership of another user, who does not know about it and there is no such work in his collection.
Since this only copy does not belong to me, I cannot exchange or burn ...
At the same time, I see all 5 copies in my wallet and they belong to me ...

My Kukai wallet:
tz1UV4EomFA8SUyE3d291YbNFb9uTS56pjzC

My NFT "Hyperloop" on hicetnunc:
http://objkt.link/87068

I reported this issue with Kukai, they confirmed there was a mistake and advised to contact here (see attachment). 

Problem 2: 
My works don't displayed in my account on hicetnunc... neither created nor collected ... only direct references to objects work... 
I need you support to fix this problem. 

Thanks an advance! 
Best wishes! 

Kuisma
![IMG_20210522_194050](https://user-images.githubusercontent.com/84636455/119236882-7b8ce900-bb42-11eb-946c-b2ca3489be02.jpg)
![IMG_20210519_213355](https://user-images.githubusercontent.com/84636455/119236891-93646d00-bb42-11eb-981e-7d7d0bb7533e.jpg)
![Screenshot_2021-05-19-01-19-31-649_com android chrome](https://user-images.githubusercontent.com/84636455/119236905-af680e80-bb42-11eb-9767-b961fcd14dff.jpg)

**Comment by kylegrover** [comment] 2021-05-24 16:31
I'd like to note that Kukai said you minted 5 editions of OBJKT#**87070** but you're asking about and linking to OBJKT#**87068**. Interesting that https://www.hicetnunc.xyz/objkt/87069 and https://www.hicetnunc.xyz/objkt/87070 show errors. There's definitely something strange going on here.

**Comment by violetforest** [comment] 2021-05-26 15:52
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/546

**Closed as completed by violetforest** 2021-05-26 15:52 UTC
Labels: bug

**Comment by KuismaArt** [comment] 2021-05-26 20:26
> I'd like to note that Kukai said you minted 5 editions of OBJKT#**87070** but you're asking about and linking to OBJKT#**87068**. Interesting that https://www.hicetnunc.xyz/objkt/87069 and https://www.hicetnunc.xyz/objkt/87070 show errors. There's definitely something strange going on here.

Exactly!..

**Comment by KuismaArt** [comment] 2021-05-26 20:28
> duplicate of #546

what does "duplicate" mean ?! this is my problem, with my particular thing ... and my money! 
about this at least something is said in #546?
Who are you and how did you help me by closing my question?

**Comment by violetforest** [comment] 2021-05-26 22:14
I am a developer in the hicetnunc team.


Your NFT is safe, its just a display issue.

You said it yourself when you said "At the same time, I see all 5 copies in my wallet and they belong to me ..."

@KuismaArt duplicate of issue means that you raised an issue that has already been raised and addressed. I sent the link to the issue where you can read what the problem is. 

The problem is that the API that we use (BCD) is reporting the wrong info. We raised the issue with BCD team via Telegram. The issue is likely a display issue only, and will resolve when upstream data is fixed. It is up to BCD to fix the issue now.

**Comment by KuismaArt** [comment] 2021-05-27 04:47
> I am a developer in the hicetnunc team.
> 
> Your NFT is safe, its just a display issue.
> 
> You said it yourself when you said "At the same time, I see all 5 copies in my wallet and they belong to me ..."
> 
> @KuismaArt duplicate of issue means that you raised an issue that has already been raised and addressed. I sent the link to the issue where you can read what the problem is.
> 
> The problem is that the API that we use (BCD) is reporting the wrong info. We raised the issue with BCD team via Telegram. The issue is likely a display issue only, and will resolve when upstream data is fixed. It is up to BCD to fix the issue now.

Excellent! Thank you very much!
Now I have the answer I was waiting for! ;-) 

Sorry... I'm just a poor artist trying to make money with my art. I invest my time in promoting my work. 
This place is the only place where I can get this help. And the answer "closed cos duplicate" was not help ...

But now I hope that the problem will be solved soon! ;-(
 
Thanks in advance ! 
Best wishes! ;-)
