### ISSUE TITLE
Cannot swap OBJKT

### ISSUE THREAD

**Issue by zur19** [hicetnunc2000/hicetnunc#787] opened 2021-05-29 20:44 UTC
Cannot swap OBJKT#101089, tried for 3 days and with different parameters...  (I have no problem with an identic objkt which I have created later, with same edition, same #number of copies, same price). I have enough TEZ on balance.

Error message: Parameters Invalid Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again.

Kukai message: Simulation error: A FAILWITH instruction was reached > FA2_INSUFFICIENT_BALANCE

**Expected behavior**
swap any amount of copies of OBJKT#101089 
e.g. 10 copies / 1 TEZ

**Desktop (please complete the following information):**
Firefox, windows 10

**Additional context**

Please include the wallet address (tz...) and/or the OBJKT number.

tz1WvKvGzP6BAPrhNd2sRFUQEtBk4f4SDV6W
OBJKT#101089

**Comment by kylegrover** [comment] 2021-06-06 00:32
@zur19 Is this still occurring or resolved now?

**Comment by zur19** [comment] 2021-06-06 10:08
hello
still occurring, this objkt got definitely stuck!!
can you remove it maybe? (I cannot burn either)
thanks

    En domingo, 6 de junio de 2021 2:32:52 CEST, Kyle Grover ***@***.***> escribió:  
 
 


@zur19 Is this still occurring or resolved now?

**Comment by MarcSimonetti** [comment] 2021-06-10 07:39
Hi, there,

I've got the very same issue.

**Comment by kylegrover** [comment] 2021-06-10 18:28
@MarcSimonetti what's your objkt# and error message? more details to help people troubleshoot.

@zur19 I see your objkts transferred to the Hic et nunc NFTs contract, you were using the hicetnunc 'swap' feature and this happened right?

**Comment by zur19** [comment] 2021-06-10 19:14
Right. Only this one objkt got stuck. The rest is okay.
    En jueves, 10 de junio de 2021 20:29:07 CEST, Kyle Grover ***@***.***> escribió:  
 
 


@MarcSimonetti what's your objkt# and error message? more details to help people troubleshoot.

@zur19 I see your objkts transferred to the Hic et nunc NFTs contract, you were using the hicetnunc 'swap' feature and this happened right?

**Comment by violetforest** [comment] 2021-06-30 20:34
Hi, are you still having this issue?

**Comment by zur19** [comment] 2021-06-30 22:42
Yes
    En miércoles, 30 de junio de 2021 22:35:13 CEST, Violet Forest ***@***.***> escribió:  
 
 


Hi, are you still having this issue?

**Comment by violetforest** [comment] 2021-06-30 22:46
it looks like they are all owned by the hicetnunc escrow wallet, so they are at least being held by HEN. I would wait for the migration to the new swap contract to be fixed and then we can see what to do then.

**Comment by KonstantFlux** [comment] 2021-08-07 02:20
Hi There, 
I have swapped out my token after minting however it is displaying not for sale. 
https://www.hicetnunc.xyz/objkt/196206
The transaction is approved https://tzkt.io/ooxHRC9BQesvPwgB3XjL3AkE2dzfq2nXwXxYFq2dZiEZ9wJL17Z
However it is still not displaying. 
I also cannot cancel the sale to burn as it is displaying not for sale. 
Please help, I had promoted a drop for 1 hour ago and now I can't follow through. 
Cheers, 
Jimmy.

**Comment by thaphuong** [comment] 2021-09-09 15:28
Hi,

There were several transactions approved. The art works showed on my collection, but somehow, when I clicked on it, the detail page is just blank. 

https://www.hicetnunc.xyz/objkt/272371
https://www.hicetnunc.xyz/objkt/272330
https://www.hicetnunc.xyz/objkt/260537

Wallet: tz1bnt5eeUV9whGXRe37F19AHdXfYfADxTYr

Thanks,

N.

**Comment by francisco-fl** [comment] 2021-09-09 18:53
https://www.hicetnunc.xyz/objkt/283769
same

**Comment by violetforest** [comment] 2021-09-13 19:13
@thaphuong hello, those objkts and profiles are showing up as restricted, meaning they were reported as copyminters

**Comment by violetforest** [comment] 2021-09-13 19:14
> https://www.hicetnunc.xyz/objkt/283769
> same


can you cancel the swaps and then burn them? this is an interactive OBJKT, are there problems in your code? Was it ever working?

**Comment by thaphuong** [comment] 2021-09-13 19:18
Bummer... so someone stole it & sold it? I thought the blockchain is supposed to prevent this type of transactions? At least, now i can see the page, but the author (fake) account is showing "restricted ". Do I have to do anything?  Thanks again for your help, Violet.
Nam

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 13, 2021 at 12:14 PM, Violet ***@***.***> wrote:   


@KonstantFlux can you cancel the swaps and then burn them? this is an interactive OBJKT, are there problems in your code? Was it ever working?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by violetforest** [comment] 2021-09-13 19:21
@thaphuong right, it is a fake account. the account holder can dispute the restricted account in the discord. you can always send the objkts to the burn wallet if you've contacted the artist and confirmed that it was a copyminted work.

**Comment by thaphuong** [comment] 2021-09-13 19:24
But i will lose the money buyimg those? Thank you for your advice.


Sent from Yahoo Mail on Android 
 
  On Mon, Sep 13, 2021 at 12:21 PM, Violet ***@***.***> wrote:   


@thaphuong right, it is a fake account. the account holder can dispute the restricted account in the discord. you can always send the objkts to the burn wallet if you've contacted the artist and confirmed that it was a copyminted work.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by violetforest** [comment] 2021-09-13 19:42
Hey yes, we aren't able to issue refunds. Please verify the seller's social media accounts before making transactions.

**Comment by melisbalci** [comment] 2021-09-26 18:32
Hello, 
D

> > https://www.hicetnunc.xyz/objkt/283769
> > same
> 
> can you cancel the swaps and then burn them? this is an interactive OBJKT, are there problems in your code? Was it ever working?

Hello
I'm having the same issue. https://www.hicetnunc.xyz/objkt/341707   My work is not restricted, why am i having this problem? I swapped this last week but still it appears as "not for sale" when I try to swap again, I get errors.

**Closed as completed** 2021-09-29 22:43 UTC
Labels: bug

**Comment by makalele09** [comment] 2021-11-19 18:06
hi sorry i'm re-opening this conversation, it's because i have the same problem in OBJKT#540281 on 18 november 2021

Error message: Parameters Invalid Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again.

Kukai message: Simulation error: A FAILWITH instruction was reached > FA2_INSUFFICIENT_BALANCE

can you help solve this problem?

**Comment by kylegrover** [comment] 2021-11-21 02:29
FA2_INSUFFICIENT_BALANCE - you don't have enough tokens to process the
transaction. This either means you don't possess the NFT in question, or
more often that you're simply out of Tezos. All transactions on the
blockchain will cost a small amount of Tezos.

**Comment by makalele09** [comment] 2021-11-21 05:03
the problem occurred in my first objkt, then I tried uploading the second objkt and it worked when I did the swap.

in the first objkt the problem, maybe it can be seen here https://hicdex.com/objkt?objkt=540281
there my OBJKT holder is KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton

maybe it can help solve this problem, i just want to do a swap in that objkt

**Comment by skenaja** [comment] 2021-11-21 13:00
The objkt in question was sent to the Burn address
https://tzstats.com/oo7h2j9UKajGGgsR1AVMjKuuYewPdkEeVN188ABRApACUyANNJ6

You will have to mint again if you want to swap the objkts.

**Comment by makalele09** [comment] 2021-11-21 15:42
so there will be two same image/work in my assets?
