### ISSUE TITLE
Burned OBJKTs are still listed in profile page

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#265] opened 2021-03-26 13:35 UTC
I know that this is probably already on the to-do list, but I just wanted to add this as an official issue. It would really be nice if NFTs owned by tz1burnburnburnburnburnburnburjAYjjX would not show up in public views anymore.

**Comment by jonobr1** [comment] 2021-03-27 17:17
The most lucrative collector! But, in all seriousness:

This perhaps isn't the best fix, but figured I'd share as way to brainstorm creative solutions. If the hicetnunc team has access to this wallet then adding attributions to its profile like "hicetnunc landfill" or something could be a nice way to reinforce the idea that the blockchain is permanent.

**Comment by crzypatchwork** [comment] 2021-03-28 21:10
the filtering was partially implemented, though there are many conditions to be considered burned. you must burn all in your possession, burning something that was distributed is another work around still which is not yet to be implemented. 

about the secret of the burn address it's an absolutely random address ;s a dummy smart contract will be created.

**Comment by dhowe** [comment] 2021-04-23 07:25
yes, really need this feature. I have a test object that is burnt,  but stuck in my profile, seems impossible to get rid of.

Wallet: tz1LBrt4eYvv82VL1d5VsxX22wAE1pxjGcym
OS: OSX 10.15.7 (19H524)
Firefox 10.15.7 (19H524)

![image](https://user-images.githubusercontent.com/737638/115834623-03021200-a448-11eb-97d8-18c7eb32ad96.png)

**Comment by skenaja** [comment] 2021-04-23 08:27
> yes, really need this feature. I have a test object that is burnt, but stuck in my profile, seems impossible to get rid of.
> 

@dhowe It's still on sale - you first need to cancel the swap, see the "Collectors" tab for cancel button

**Comment by skenaja** [comment] 2021-04-23 08:29
If an objkt is fully owned by the tz1burn address, it now no longer appears in the profile creations page. 

Closing issue.

**Closed as completed by skenaja** 2021-04-23 08:29 UTC
Labels: bug

**Comment by dhowe** [comment] 2021-04-23 11:12
So I have both cancelled the swap and transferred the object (manually) to the tz1burn address, but still it shows in my creations page. When I attempt to 'cancel' again, the transaction fails.

**Comment by skenaja** [comment] 2021-04-24 09:57
@dhowe Looks like there was a delay in the upstream API provider that aggregates blockchain data and hence the list of holders was showing as out of date. The lovely photo of Diego is now correctly showing as wholly owned by Burn Wallet. (as confirmed by this [API call](https://better-call.dev/v1/contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders?token_id=42591))

**Comment by dhowe** [comment] 2021-04-25 04:16
thanks much @skenaja
may diego rest in (blockchain) peace
