### ISSUE TITLE
broken links to all my collections

### ISSUE THREAD

**Issue by Oaknarrow** [hicetnunc2000/hicetnunc#950] opened 2021-06-25 21:08 UTC
**Describe the bug**
none of the links to my "creations" work. leads potential collectors to a blank or black screen without anything there. 
**To Reproduce**
1. Go to 'creations'
2. Click on 'anything'
3. See error

**Expected behavior**
people should be able to buy or see my creations

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 91.0.4472.114 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iphone
 - OS: 14.6
 - Browser safari + Chrome
 

**Additional context**
this issue has been ongoing for the last 48hrs. ive tried to sync and unsync my device. cleared all caches. still not working.

**Comment by Oaknarrow** [comment] 2021-06-25 21:09
![blank](https://user-images.githubusercontent.com/86497459/123485411-e8225a00-d5be-11eb-8779-dee946fb643d.PNG)
![collection](https://user-images.githubusercontent.com/86497459/123485413-e9ec1d80-d5be-11eb-86eb-0bb15f6b5cfe.PNG)

**Comment by Oaknarrow** [comment] 2021-06-26 15:16
Hey, can someone please assist me here? this is a big issue and I'm losing money on not being able to sell any of my creations and grab collectible pieces that have value. is this now going on 4 days

**Comment by Oaknarrow** [comment] 2021-06-26 19:31
hello? just looking for any type of response please. it is really affecting my sales. i am getting numerous DMs daily about people trying to buy my art and I can't sell it to them. you took my money to mint the objects, so can you please sort this out as soon as possible

thanks 
oak

**Comment by skenaja** [comment] 2021-06-27 10:47
The profile page appears be working:
https://www.hicetnunc.xyz/tz/tz1iXaGmF2mnG52EP2sPJC1c8SYjDmGZnGRS/creations
![image](https://user-images.githubusercontent.com/510285/123541490-c8b13b80-d73c-11eb-9cae-8dcb2c555e73.png)

On objkt pages, eg https://www.hicetnunc.xyz/objkt/149987 I get the blank screen too. I can see this error in the console - `2.3e246035.chunk.js:2 URIError: Pathname "/O%²K" could not be decoded. This is likely caused by an invalid percent-encoding.`

This is caused by a limitation of usernames where special characters are not currently supported - please change it via https://www.hicetnunc.xyz/config

**Comment by violetforest** [comment] 2021-06-30 19:55
i'm going to close this, please respond if you still need help and I will reopen it

**Closed as completed by violetforest** 2021-06-30 19:55 UTC
Labels: bug

**Comment by Oaknarrow** [comment] 2021-06-30 19:58
Thank you so much Violet for all your help!!!

Cheers to you and your amazing team

Oak
