### ISSUE TITLE
Objkt missing from creations page, can't swap, cancel, burn

### ISSUE THREAD

**Issue by Wilco1975** [hicetnunc2000/hicetnunc#317] opened 2021-03-30 07:23 UTC
https://www.hicetnunc.xyz/objkt/16803
I minted this last night with the intention of giving some away to artists i owed from #objkt4objkt event selling the rest but having the first 10 be free.
I minted 120.  
Sent one to a friend
swapped 10@0tez
swapped 100@1tez
continued to send free ones to other artists from what I thought was the remaining 9

now the Objkt is gone from my creations page (still visible in the collections of those that received it) and only accessible via the link above.  Now it says "not for sale" and I can't swap/cancel/burn

Any help is appreciated, thank you

**Comment by skenaja** [comment] 2021-03-30 10:05
Looks like a duplicate of #280

You can see that one of the editions was burned, as the burn wallet id [appears in the API results](https://api.better-call.dev/v1/contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders?token_id=16803) for that objkt id

**Comment by Wilco1975** [comment] 2021-04-04 09:09
Well whatever fix you made , made it appear on my creations page again and then I just reswapped the OBJKT and everything is fine now. Thank you.

**Closed as completed** 2021-04-07 01:57 UTC
