### ISSUE TITLE
Can't swap after canceling a swap

### ISSUE THREAD

**Issue by dblock** [hicetnunc2000/hicetnunc#485] opened 2021-04-12 16:00 UTC
**Describe the bug**

I was trying to lower the price of a swap. Since there's no way to do that, I tried to cancel the swap, and wanted to swap again. 

Swap button does not appear after cancelling a swap in https://www.hicetnunc.xyz/objkt/28576.

**To Reproduce**

1. Mint and swap an object.
2. Cancel the swap.
3. No longer shows number of editions nor can swap again.

**Expected behavior**

Expect to see a swap button (and possibly number of editions, which was 50 the first time around).

**Screenshots**

<img width="827" alt="Screen Shot 2021-04-12 at 11 57 59 AM" src="https://user-images.githubusercontent.com/542335/114424671-59d53500-9b86-11eb-9767-64e3d38d9eda.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 89.0.4389.114 (Official Build) (x86_64)

**Additional context**

https://www.hicetnunc.xyz/objkt/28576
tz1ivFsNqtfLTSDh7uzqJ6pArNRG13pkJt4a

possibly related to #477

**Comment by dblock** [comment] 2021-04-12 20:57
Looks like does get resolved over time, see https://github.com/hicetnunc2000/hicetnunc/issues/477#issuecomment-817956725 - for a user we probably want to be able to show something like a "please wait, this will be swappable soon"

**Comment by andrevenancio** [comment] 2021-04-12 22:41
Is this a NFT You minted or you're reselling? Because there's an issue with a API we're using where we can get a list of "owners" for the token. Which means if you're not the creator, the platform can't tell if you own that token or not. Should be fixed soon. It's a 3rd party.

**Comment by dblock** [comment] 2021-04-12 22:47
> Is this a NFT You minted or you're reselling? Because there's an issue with a API we're using where we can get a list of "owners" for the token. Which means if you're not the creator, the platform can't tell if you own that token or not. Should be fixed soon. It's a 3rd party.

I minted this one.

**Comment by skenaja** [comment] 2021-04-19 10:59
This was caused by delays in upstream API provider to update the list of holders. Closing, as they have mostly been resolved, and the swap button is now permanently available, even when the list of holders is out-of-date.

**Closed as completed by skenaja** 2021-04-19 10:59 UTC
Labels: bug, duplicate
