### ISSUE TITLE
Wrong total editions amount

### ISSUE THREAD

**Issue by mescalina** [hicetnunc2000/hicetnunc#633] opened 2021-05-02 05:48 UTC
I've noticed that an objkt I published with 500 editions for the O4O event is now showing 520 editions instead of 500.
This is the objkt:
https://www.hicetnunc.xyz/objkt/45200

**Comment by kylegrover** [comment] 2021-05-02 19:46
A (probably) related bug I noticed today- this OBJKT shows 265/217 editions available https://www.hicetnunc.xyz/objkt/43047

**Comment by andrevenancio** [comment] 2021-05-07 02:54
investigating

**Comment by skenaja** [comment] 2021-05-07 09:03
Likely to be #546

**Comment by mescalina** [comment] 2021-05-10 04:49
> Likely to be #546

I'm not sure it's related, originally for some time the total listed amount was correct, 500 editions, than days or even a couple of weeks later it started to show 520 instead of 500.

**Comment by violetforest** [comment] 2021-05-26 15:52
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/546

**Closed as completed by violetforest** 2021-05-26 15:52 UTC
Labels: bug
