### ISSUE TITLE
Allow hiding of objects on 'creations' page

### ISSUE THREAD

**Issue by dhowe** [hicetnunc2000/hicetnunc#588] opened 2021-04-26 04:29 UTC
You've created an object,  but you don't want to sell it or display it yet. Instead you can hide the object until you are ready.

Alternatively, objects which are not for sale would not show up.

See #593

**Comment by tarwin** [comment] 2021-04-28 16:56
I'd suggest you burn the OBJKT until you are ready to sell?

**Comment by dhowe** [comment] 2021-05-05 08:53
Burning does not help in cases where the object has been collected (ticket #593 describes such a scenario). 

For example, you put a test object up for collection, maybe for 0 Tez, and someone collects it. Now it is locked onto your creations page for, as best I can tell, ETERNITY. 

It is _very important,_ if you want artists to use this platform, that they can control how their work is represented, and, specifically, what their "creations" page looks like.

It seems that the only option in the above scenario is to abandon the wallet, remove the artist info and links (if this is even possible?) and then create a new wallet and start from scratch. This is NOT a good option

**Comment by violetforest** [comment] 2021-05-26 18:09
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/285

**Closed as completed by violetforest** 2021-05-26 18:09 UTC
Labels: feature-request
