### ISSUE TITLE
OBJKT 126929

### ISSUE THREAD

**Issue by void3gp** [hicetnunc2000/hicetnunc#867] opened 2021-06-11 19:24 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by andrevenancio** [comment] 2021-06-12 22:53
Hi @void3gp thank you for taking the time to submit an issue, however with the information you shared (OBJKT number) we dont have much information to understand what the issue is. Closing this issue for now, but feel free to come back with more details and we'll re-open this issue.

**Closed as completed by andrevenancio** 2021-06-12 22:53 UTC
Labels: bug
