### ISSUE TITLE
Create better social media embeddings

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#322] opened 2021-03-30 09:59 UTC
It would be nice if when embedding a direct link to OBJKT page on twitter or other social media channels the preview would show a thumbnail of the work instead of the default icon and at least the title and parts of the description would be shown. I guess this might be difficult for some mime-types, but it would be great if someone could have another look at this and see if it can be improved.

This is what we are currently looking at:
![image](https://user-images.githubusercontent.com/182098/112971214-4b7f2600-914f-11eb-9392-e930ca0765c5.png)

**Comment by skenaja** [comment] 2021-03-30 10:07
This looks like a duplicate of #159

**Comment by Quasimondo** [comment] 2021-03-30 10:37
Ah sorry, I did a search before posting, but it looks like i did not use the right keywords.

**Closed as completed** 2021-03-30 10:38 UTC
