### ISSUE TITLE
burn doesn't show how many copies you have

### ISSUE THREAD

**Issue by andrevenancio** [hicetnunc2000/hicetnunc#900] opened 2021-06-17 01:11 UTC
Burn shows user holds 0 copies. Needs to read from `supply`

![Screenshot 2021-06-17 at 02 10 13](https://user-images.githubusercontent.com/1734502/122315112-55742200-cf11-11eb-877e-0683d4479b64.png)

**Comment by maneda** [comment] 2021-06-21 15:43
Hi. I also had this issue on a couple of Objects but seemed to get around it by clicking on the "collectors" tab and then clicking the "cancel" button. After a few minutes the burn tab showed that I owned all the editions and I was able to burn them.

**Comment by violetforest** [comment] 2021-06-22 17:31
I cant reproduce this. was it fixed? @andrevenancio

**Comment by violetforest** [comment] 2021-06-22 17:39
This was a display error but it should be fixed now. Try clearing your browser cache.

If it still doesn't work, you can still burn all them even though it says 0. Go ahead and try it.

In the future, always check whats in your wallet and use that as confirmation. There should be 9988 in your wallet.

If you need anything else Ill open the issue back up

**Closed as completed by violetforest** 2021-06-22 17:39 UTC
Labels: bug
