### ISSUE TITLE
HEN shows 11 editions when I only minted 1

### ISSUE THREAD

**Issue by neverhood311** [hicetnunc2000/hicetnunc#618] opened 2021-04-29 22:08 UTC
**Describe the bug**
I minted 1 edition of an item, then swapped that 1 edition (https://www.hicetnunc.xyz/objkt/55211). When I go to the OBJKT page, it shows that there are 11: 1 owned by me (tz1NQZ4jDzTwojd58y4PTeETxbQXvUeQjuH1), and 10 owned by some other address, (tz1MBXZBxPT6orrMCNFifJr396zkZJJDkzEJ)
Here's the ID for the mint operation: https://tzkt.io/op9pejDuhaRPisL8P43tRV534sdiTJNXJ8uP6Yi815RnMnQPKy5
And here's the ID for the swap operation: https://tzkt.io/ooR1YMNWDgrAzReJ6wsdXJHNLAPAYc89LLLA7XeLkvhQzSqEQhJ

**Expected behavior**
Since I minted only 1 edition, I expected there to be only one listed in both the Editions counter and in the Collectors list

**Screenshots**
![image](https://user-images.githubusercontent.com/4615170/116624351-6a6b0680-a90d-11eb-810f-eee831b3bf5a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by ucodia** [comment] 2021-04-30 01:03
For some reason, the 10 extra editions appear to be attributed to another wallet `tz1MBXZBxPT6orrMCNFifJr396zkZJJDkzEJ`
Though it does not show on that account collection: https://www.hicetnunc.xyz/tz/tz1MBXZBxPT6orrMCNFifJr396zkZJJDkzEJ

I noticed that the [mint transaction of 1 edition from OP](https://tzkt.io/op9pejDuhaRPisL8P43tRV534sdiTJNXJ8uP6Yi815RnMnQPKy5) occurred at the same exact time wallet `tz1MBXZBxPT6orrMCNFifJr396zkZJJDkzEJ` was [minting 10 editions](https://tzkt.io/ooDN6vBcB7m5ya3twH5GEyvpA7UGGu3fvMCYk93SpwerkCM8b6P).

**Comment by mescalina** [comment] 2021-04-30 07:36
This is a quite interesting situation, I'm following.

**Comment by skenaja** [comment] 2021-04-30 08:36
This looks like a re-occurrence of #546. I'll chase the Baking Bad team to see if they have an update.

**Comment by skenaja** [comment] 2021-04-30 09:05
Here are the 2 swap operations:
https://better-call.dev/mainnet/opg/ooR1YMNWDgrAzReJ6wsdXJHNLAPAYc89LLLA7XeLkvhQzSqEQhJ/contents
https://better-call.dev/mainnet/opg/ontZyzMwAWV7nawHWm9vC1kFX6BFcnXkYy5184peKCbwotngTvh/contents

BCD has indexed them both under 55211
https://api.better-call.dev/v1/contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders?token_id=55211

**Comment by skenaja** [comment] 2021-04-30 10:43
Vague, but promising response from BB team:

`There will be a major update (currently in staging) that will fix this issue and inferred token transfers in general.`

**Comment by andrevenancio** [comment] 2021-05-07 03:02
has this been fixed? because I can see that there was 11 editions minted
https://51rknuvw76.execute-api.us-east-1.amazonaws.com/dev/objkt?id=55211 on the total

**Comment by skenaja** [comment] 2021-05-07 06:50
It's still an ongoing issue. From BB team yesterday "Fix is on its way, currently reindexing everything from scratch"

**Comment by violetforest** [comment] 2021-05-26 16:04
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/546

**Closed as completed** 2021-05-26 16:04 UTC
Labels: bug
