### ISSUE TITLE
Full screen button doesn't work for html content (Safari)

### ISSUE THREAD

**Issue by arielm** [hicetnunc2000/hicetnunc#377] opened 2021-04-02 11:05 UTC
Hi, I have tried the new full-screen button on [OBJKT#18474](https://www.hicetnunc.xyz/objkt/18474) and it's not working.

The following error is showing in the JS console:
> TypeError: document.documentElement.requestFullscreen is not a function. (In 'document.documentElement.requestFullscreen()', 'document.documentElement.requestFullscreen' is undefined)

It occurs on Safari 13.1.1 / macOS.

**Comment by Pamicel** [comment] 2021-04-02 12:18
Hi, this is a duplicate of issue #358 addressed by [pull request 369](https://github.com/hicetnunc2000/hicetnunc/pull/369)

**Closed as completed** 2021-04-02 13:13 UTC
