### ISSUE TITLE
Posibility to favorite artists 

### ISSUE THREAD

**Issue by PureSpider** [hicetnunc2000/hicetnunc#224] opened 2021-03-23 12:24 UTC
As the title says - a followup for this would be to have a separate "favorite" stream, next to "all".

**Comment by PureSpider** [comment] 2021-03-24 10:54
See also #49

**Comment by gianflavio** [comment] 2021-05-16 06:49
Yeah, a way to follow or favorite artists would be great. Maybe even a Timeline or filter where you only see your favorited artists' creations or collections.

**Comment by violetforest** [comment] 2021-05-26 18:05
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/49

**Closed as completed by violetforest** 2021-05-26 18:05 UTC
Labels: feature-request
