### ISSUE TITLE
Allow collector address to be passed into query parameters

### ISSUE THREAD

**Issue by BvdMerwe** [hicetnunc2000/hicetnunc#883] opened 2021-06-14 21:02 UTC
It would be really cool to have the address that has collected a piece be accessible to an interactive objkt. This could allow for pieces to be personalised to the collectors, viewers and creators.

**Comment by dribnet** [comment] 2021-06-16 10:25
This is a popular request and I believe a duplicate of #513. Note however that this feature only makes sense for 1/1 OBJKTs because with more than one in the edition the token is partially fungible and doesn't support a one to one mapping between tokens and owners. Passing a complete list of "owners" for a token might seem to be a workaround, but this is not really feasible as the token can have thousands of owners and so the querystring blows up. To also support these multiple editions a simpler isOwner=True flag has been suggested and could be applied to slightly different use cases than you proposed. However I 100% agree with you that dedicated owner=tzFoo parameter for 1/1 minted OBJKTs would also be an awesome feature to support and would enable some really interesting custom behaviours.

**Comment by andrevenancio** [comment] 2021-06-17 01:14
You can now do this manually on your NFT. There's a new parameter called objkt which shows the OBJKT number. You can check that number against any API like https://hicdex.com/ to get this info. closing

**Closed as completed by andrevenancio** 2021-06-17 01:14 UTC
Labels: feature-request
