### ISSUE TITLE
Use images lazy loading to avoid extra data and browser crash

### ISSUE THREAD

**Issue by thiagodini** [hicetnunc2000/hicetnunc#745] opened 2021-05-24 19:03 UTC
When we try to see our gallery or the feed for new objkts, the browser tries to load a lot of content, doing more job than necessary most of the time. Maybe a simple solution to this case can be the new native HTML5 lazy loading, like these examples: 
https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading

**Comment by andrevenancio** [comment] 2021-05-25 13:23
The site already implements lazy loading. The issue is that currently we display the art that the user uploads. so if they upload a 4k image that's the image that gets served. there is a parallel stream of work where we're generating lower resolution thumbnails that should help speed up things, its currently being developed.

**Comment by thiagodini** [comment] 2021-05-25 14:11
Nice, @andrevenancio! But for me the lazy loading still not working, maybe add this HTML5 solution can 
maximize the compatibility with this technique. 

Check the attachment... 
And thank you for all the job done! :) 

![Screenshot_2021-05-24 hic et nunc](https://user-images.githubusercontent.com/1469596/119512321-954c4d00-bd49-11eb-9beb-ba91ff97a30d.png)

**Comment by violetforest** [comment] 2021-05-26 18:16
closing -- this is in development

**Closed as completed by violetforest** 2021-05-26 18:16 UTC
Labels: feature-request

**Comment by thiagodini** [comment] 2021-06-09 15:26
#848 I make a pull request to this issue, I hope to help!
