### ISSUE TITLE
The preview button for minting my nft isn’t working?

### ISSUE THREAD

**Issue by cryptoaliens** [hicetnunc2000/hicetnunc#694] opened 2021-05-13 09:33 UTC
The mobile version won’t let me mint anything?
I load all the info Into the boxes and the button still remains shaded and un clickable 
I can’t mint anything I am connected to my wallet and I have a balance

**Comment by kylegrover** [comment] 2021-05-15 22:01
I think this isn't actionable until we know a lot more. Can you join the discord and post in the #help channel for a faster discussion?

**Comment by cryptoaliens** [comment] 2021-05-16 12:01
I did they told me to use a desktop computer

**Comment by violetforest** [comment] 2021-05-26 15:44
@cryptoaliens Is this still a problem? Do you have a screenshot?

**Comment by violetforest** [comment] 2021-05-26 16:18
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/526

**Comment by cryptoaliens** [comment] 2021-05-26 17:43
I can get a screen shot give me a minute thanks. I’m pretty sure it will
work if I use my desktop and temple wallet

>

**Comment by cryptoaliens** [comment] 2021-05-26 17:51
I can’t get past this window I have funded the account

**Comment by violetforest** [comment] 2021-05-26 17:55
@cryptoaliens please send a screenshot

**Comment by violetforest** [comment] 2021-06-30 20:52
closing due to inactivity, let me know if you still need help and I will reopen

**Closed as completed by violetforest** 2021-06-30 20:52 UTC
Labels: bug
