### ISSUE TITLE
Not showing my artwork on hic et nunc and this code apears "(http 500)"

### ISSUE THREAD

**Issue by MahdiNjt** [hicetnunc2000/hicetnunc#710] opened 2021-05-17 15:30 UTC
[edited to move full error message from title to issue text:

```
 <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>TypeError: Cannot read property &#39;creators&#39; of undefined<br> &nbsp; &nbsp;at readObjkt (/var/task/lib/router/readObjkt.js:14:54)<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre> </body> </html>"
```

**Comment by skenaja** [comment] 2021-05-17 22:04
This is a duplicate of #683 (the error message from the API is now showing on-screen)

Work is underway to improve reliability of the collection page.

**Closed as completed by skenaja** 2021-05-17 22:04 UTC
Labels: bug
