### ISSUE TITLE
objekt 40062 - 15 more copies minted without my permission

### ISSUE THREAD

**Issue by superrobottyson** [hicetnunc2000/hicetnunc#678] opened 2021-05-11 02:11 UTC
**Describe the bug**
I minted 20 copies of objkt 40062, then listed them for 1 Tez each. Now when I view the asset it say that there are 35 copies of the item and I do not own 15 of them. 

**To Reproduce**
view objkt 40062

**Expected behavior**
I was hoping to burn all copies of the item and re-mint. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows or iOS 

**Additional context**
Please include the wallet address tz1cYtiGag9S7WE8n2inJfLDTit6fdNWjyP7

**Comment by mtyka** [comment] 2021-05-13 22:02
This looks like a duplicate of this issue: https://github.com/hicetnunc2000/hicetnunc/issues/546 - a fix is on it's way.

**Comment by mtyka** [comment] 2021-05-13 22:03
Closing this for now to declutter the bugs list.

**Closed as completed by mtyka** 2021-05-13 22:03 UTC
Labels: bug
